[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio", "--config", "<path to cspell.json>"]

# ========================
# Lean
# ========================
[[language]]
name = "lean"
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
indent = { tab-width = 2, unit = "  " }
language-servers = ["cspell"]


# ========================
# Lean
# ========================
[[language]]
name = "elisp"
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
indent = { tab-width = 2, unit = "  " }
language-servers = ["cspell"]

# ========================
# Toml
# ========================
[[language]]
name = "toml"
auto-format = true
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
indent = { tab-width = 2, unit = "  " }
language-servers = ["cspell"]

# ========================
# Plant UML
# ========================
[[language]]
name = "plantuml"
scope = "source.plantuml"
auto-format = true
comment-tokens = "'"
indent = { tab-width = 4, unit = "    " }
file-types = ["plantuml", "puml"]
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
language-servers = ["cspell"]

# ========================
# Ocaml
# ========================
[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
  ] }
language-servers = ["ocamllsp", "cspell"]

# ========================
# Rust
# ========================
[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "cspell"]

# ========================
# Racket
# ========================
[[language]]
name = "racket"
auto-format = true

# ========================
# Typst
# ========================
[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "never" }

[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typst", "typ"]
indent = { tab-width = 2, unit = "  " }
comment-token = "//"
injection-regex = "typ(st)?"
roots = ["typst.toml"]
language-servers = [ "tinymist", "cspell" ]
formatter = { command = "sed", args = ["s/[ \t]*$//"] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'$' = '$'

[[grammar]]
name = "typst"
source.git = "https://github.com/uben0/tree-sitter-typst"
source.rev = "master"

# ========================
# Latex
# ========================
[[language]]
name = "haskell"
auto-format = true
formatter = { command = "ormolu", args = ["--stdin-input-file", ""] }

# ========================
# Latex
# ========================
[[language]]
name = "latex"
auto-format = true
formatter = { command = "tex-fmt", args = ["--stdin"] }
language-servers = [ "texlab", "cspell" ]
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'$' = '$'

# ========================
# Web development
# ========================
[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "html"
auto-format = false
language-servers = ["vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls" ]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { astro = "html", "*.astro" = "html" } }


# ========================
# C-Sharp
# ========================
[[language]]
name = "c-sharp"
file-types = ["cs", "razor"]
